<?php

namespace App\Controller\Admin;

use App\Entity\DureeSejour;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class DureeSejourCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        // TODO: Implement getEntityFqcn() method.
        return DureeSejour::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return parent::configureFields($pageName); // TODO: Change the autogenerated stub
    }
}