<?php

namespace App\Controller\Admin;

use App\Entity\Passager;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class PassagerCrudController extends AbstractCrudController
{

    public static function getEntityFqcn(): string
    {
        // TODO: Implement getEntityFqcn() method.
        return Passager::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return parent::configureFields($pageName); // TODO: Change the autogenerated stub
    }
}